import test from 'node:test';
import assert from 'node:assert/strict';
import { makeRoom, makeDeck, join, command, view, GameError } from '../lib/engine.js';
import { create, read, mutate } from '../lib/storage.js';
const tokenA='a'.repeat(64),tokenB='b'.repeat(64);
const setup=(pack='classic',options={})=>{const r=makeRoom('TESTAB',pack,'Alice',tokenA,options);join(r,'Bob',tokenB);return r;};
function allCards(r){return [...r.deck,...r.discard,...r.table,...r.players.flatMap(p=>p.hand)];}
function invariant(r,count){const cards=allCards(r);assert.equal(cards.length,count);assert.equal(new Set(cards.map(c=>c.id)).size,count);}
test('Classic and Uno packs have correct composition and unique identifiers',()=>{assert.equal(makeDeck('classic').length,52);const uno=makeDeck('uno');assert.equal(uno.length,108);assert.equal(uno.filter(c=>c.color==='wild').length,8);assert.equal(makeDeck('uno',4).length,432);assert.throws(()=>makeDeck('bad'),GameError);assert.throws(()=>makeDeck('classic',5),GameError);});
test('Drawing is free: both players draw successively, with no turns',()=>{const r=setup();command(r,tokenA,{type:'draw',count:2});command(r,tokenA,{type:'draw'});command(r,tokenB,{type:'draw',count:4});assert.equal(r.players[0].hand.length,3);assert.equal(r.players[1].hand.length,4);invariant(r,52);});
test('Hands, deck values, tokens and face-down table values are private',()=>{const r=setup();command(r,tokenA,{type:'draw'});command(r,tokenB,{type:'draw'});const hidden=r.players[0].hand[0];command(r,tokenA,{type:'place',cardId:hidden.id,faceUp:false});const data=view(r,tokenB);assert.equal(data.hand.length,1);assert.equal(data.table[0].value,undefined);assert.equal(data.table[0].suit,undefined);assert.equal(data.deck,undefined);assert.equal(JSON.stringify(data).includes('tokenHash'),false);assert.equal(data.players[0].hand,undefined);command(r,tokenB,{type:'flip',cardId:hidden.id,expectedFaceUp:false});assert.equal(view(r,tokenB).table[0].value,hidden.value);});
test('Cannot steal a private hand card through place, give or discard',()=>{const r=setup();command(r,tokenA,{type:'draw'});const id=r.players[0].hand[0].id;for(const type of ['place','discard','return','give'])assert.throws(()=>command(r,tokenB,{type,cardId:id,playerId:r.players[0].id}),GameError);assert.throws(()=>view(r,'forged'),GameError);invariant(r,52);});
test('Place, move, flip, take, give, discard, recycle and return conserve cards',()=>{const r=setup();command(r,tokenA,{type:'draw',count:3});const id=r.players[0].hand[0].id;command(r,tokenA,{type:'place',cardId:id});command(r,tokenB,{type:'move',cardId:id,x:70,y:80});command(r,tokenB,{type:'flip',cardId:id});command(r,tokenB,{type:'take',cardId:id});command(r,tokenB,{type:'give',cardId:id,playerId:r.players[0].id});command(r,tokenA,{type:'discard',cardId:id});command(r,tokenB,{type:'take',source:'discard'});command(r,tokenB,{type:'return',cardId:id});const id2=r.players[0].hand[0].id;command(r,tokenA,{type:'discard',cardId:id2});command(r,tokenB,{type:'recycle'});invariant(r,52);});
test('Palmier circle stays face-down and table is shared',()=>{const r=setup('classic',{layout:'circle'});assert.equal(r.table.length,20);assert.equal(r.deck.length,32);assert.ok(r.table.every(c=>!c.faceUp));assert.ok(view(r,tokenA).table.every(c=>!c.value));command(r,tokenB,{type:'take',cardId:r.table[0].id});invariant(r,52);});
test('Exhaustion, invalid position and repeated flips do not lose cards in stored mutations',async()=>{const r=setup();await create({...r,code:'ERRORS'});await assert.rejects(mutate('ERRORS',r=>command(r,tokenA,{type:'draw',count:53})),GameError);await mutate('ERRORS',r=>command(r,tokenA,{type:'draw'}));const {room:before}=await read('ERRORS');const id=before.players[0].hand[0].id;await assert.rejects(mutate('ERRORS',r=>command(r,tokenA,{type:'place',cardId:id,x:NaN})),GameError);const {room:after}=await read('ERRORS');assert.equal(after.players[0].hand.length,1);invariant(after,52);});
test('Only host resets; leaving returns hand and transfers host; rejoin works',()=>{const r=setup();command(r,tokenA,{type:'draw',count:3});assert.throws(()=>command(r,tokenB,{type:'reset'}),GameError);command(r,tokenA,{type:'leave'});assert.equal(r.host,r.players[1].id);assert.equal(r.deck.length,52);join(r,'Alice',tokenA);assert.equal(r.players.filter(p=>p.active).length,2);command(r,tokenB,{type:'reset'});invariant(r,52);});
test('100 players join, with private projections, and 101st is rejected',()=>{const r=makeRoom('HUNDRE','uno','P0',tokenA,{copies:4});for(let n=1;n<100;n++)join(r,'P'+n,'token-'+n);assert.equal(r.players.length,100);command(r,tokenA,{type:'deal',count:3});assert.ok(r.players.every(p=>p.hand.length===3));assert.equal(view(r,'token-99').hand.length,3);assert.throws(()=>join(r,'P101','extra'),GameError);invariant(r,432);});
test('Concurrent draws serialize without duplicates; storage survives subsequent reads',async()=>{const r=makeRoom('LOADAB','uno','Host',tokenA,{copies:4});await create(r);await Promise.all(Array.from({length:100},()=>mutate('LOADAB',room=>command(room,tokenA,{type:'draw'}))));const {room:latest}=await read('LOADAB');assert.equal(latest.players[0].hand.length,100);assert.equal(latest.version,101);invariant(latest,432);});
